
import os
import sys
from pathlib import Path

# Add project root to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from video_creation.media.image_generator import generate_image
from utils.logger import log
import config

def main():
    print("Testing Image Generation...")
    print(f"Model: {config.IMAGE_MODEL}")
    
    prompt = "A futuristic newsroom with glowing screens, cinematic lighting, 8k, photorealistic"
    output = Path("test_image_gen.png")
    
    try:
        path = generate_image(prompt, str(output))
        if path:
            print(f"SUCCESS: Image generated at {path}")
            # Check if it's a real image or fallback gradient
            # We can't easily check visually, but file size might indicate
            size = Path(path).stat().st_size
            print(f"File size: {size} bytes")
            if size < 5000: # Gradient fallbacks are usually small pngs? Or maybe generated by PIL.
                print("WARNING: File size is small, might be a fallback/solid color.")
        else:
            print("FAILURE: generate_image returned None")
    except Exception as e:
        print(f"ERROR: {e}")

if __name__ == "__main__":
    main()
